---
abstract: 'scrape mobile carrier information'
author:
  - 'Tokuhiro Matsuno <tokuhirom gmail com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  LWP::Online: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MobileCarrierJP
no_index:
  directory:
    - inc
    - t
recommends:
  CAM::PDF: 0
requires:
  Exporter: 0.60
  Filter::Util::Call: 0
  HTML::Selector::XPath: 0.03
  HTML::TableExtract: 0
  LWP::UserAgent: 5.834
  URI: 0
  Web::Scraper: 0.24
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/www-mobilecarrierjp.git
version: 0.41
