--- 
abstract: scrape mobile carrier information
author: 
  - Tokuhiro Matsuno <tokuhirom gmail com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-MobileCarrierJP
no_index: 
  directory: 
    - inc
    - t
recommends: 
  CAM::PDF: 0
requires: 
  HTML::Selector::XPath: 0.03
  Web::Scraper: 0.24
version: 0.07
