---
abstract: 'scrape mobile carrier information'
author:
  - 'Tokuhiro Matsuno <tokuhirom gmail com>'
build_requires:
  LWP::Online: 1.07
  Test::Base: 0
  Test::More: 0.96
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.5, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MobileCarrierJP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  WWW::MobileCarrierJP:
    file: lib/WWW/MobileCarrierJP.pm
    version: 0.64
  WWW::MobileCarrierJP::AirHPhone::CIDR:
    file: lib/WWW/MobileCarrierJP/AirHPhone/CIDR.pm
  WWW::MobileCarrierJP::Declare:
    file: lib/WWW/MobileCarrierJP/Declare.pm
  WWW::MobileCarrierJP::DoCoMo::CIDR:
    file: lib/WWW/MobileCarrierJP/DoCoMo/CIDR.pm
  WWW::MobileCarrierJP::DoCoMo::Display:
    file: lib/WWW/MobileCarrierJP/DoCoMo/Display.pm
  WWW::MobileCarrierJP::DoCoMo::Flash:
    file: lib/WWW/MobileCarrierJP/DoCoMo/Flash.pm
  WWW::MobileCarrierJP::DoCoMo::HTMLVersion:
    file: lib/WWW/MobileCarrierJP/DoCoMo/HTMLVersion.pm
  WWW::MobileCarrierJP::DoCoMo::Java:
    file: lib/WWW/MobileCarrierJP/DoCoMo/Java.pm
  WWW::MobileCarrierJP::DoCoMo::PictogramInfo:
    file: lib/WWW/MobileCarrierJP/DoCoMo/PictogramInfo.pm
  WWW::MobileCarrierJP::DoCoMo::UserAgent:
    file: lib/WWW/MobileCarrierJP/DoCoMo/UserAgent.pm
  WWW::MobileCarrierJP::EZWeb::CIDR:
    file: lib/WWW/MobileCarrierJP/EZWeb/CIDR.pm
  WWW::MobileCarrierJP::EZWeb::DeviceID:
    file: lib/WWW/MobileCarrierJP/EZWeb/DeviceID.pm
  WWW::MobileCarrierJP::EZWeb::Model:
    file: lib/WWW/MobileCarrierJP/EZWeb/Model.pm
  WWW::MobileCarrierJP::EZWeb::PictogramInfo:
    file: lib/WWW/MobileCarrierJP/EZWeb/PictogramInfo.pm
  WWW::MobileCarrierJP::Softbank::CIDR:
    file: lib/WWW/MobileCarrierJP/Softbank/CIDR.pm
  WWW::MobileCarrierJP::Softbank::Display:
    file: lib/WWW/MobileCarrierJP/Softbank/Display.pm
  WWW::MobileCarrierJP::Softbank::Flash:
    file: lib/WWW/MobileCarrierJP/Softbank/Flash.pm
  WWW::MobileCarrierJP::Softbank::HTTPHeader:
    file: lib/WWW/MobileCarrierJP/Softbank/HTTPHeader.pm
  WWW::MobileCarrierJP::Softbank::Java:
    file: lib/WWW/MobileCarrierJP/Softbank/Java.pm
  WWW::MobileCarrierJP::Softbank::PictogramInfo:
    file: lib/WWW/MobileCarrierJP/Softbank/PictogramInfo.pm
  WWW::MobileCarrierJP::Softbank::Service:
    file: lib/WWW/MobileCarrierJP/Softbank/Service.pm
  WWW::MobileCarrierJP::ThirdForce::CIDR:
    file: lib/WWW/MobileCarrierJP/ThirdForce/CIDR.pm
  WWW::MobileCarrierJP::ThirdForce::Display:
    file: lib/WWW/MobileCarrierJP/ThirdForce/Display.pm
  WWW::MobileCarrierJP::ThirdForce::Flash:
    file: lib/WWW/MobileCarrierJP/ThirdForce/Flash.pm
  WWW::MobileCarrierJP::ThirdForce::HTTPHeader:
    file: lib/WWW/MobileCarrierJP/ThirdForce/HTTPHeader.pm
  WWW::MobileCarrierJP::ThirdForce::Java:
    file: lib/WWW/MobileCarrierJP/ThirdForce/Java.pm
  WWW::MobileCarrierJP::ThirdForce::PictogramInfo:
    file: lib/WWW/MobileCarrierJP/ThirdForce/PictogramInfo.pm
  WWW::MobileCarrierJP::ThirdForce::Service:
    file: lib/WWW/MobileCarrierJP/ThirdForce/Service.pm
  WWW::MobileCarrierJP::ThirdForce::UserAgent:
    file: lib/WWW/MobileCarrierJP/ThirdForce/UserAgent.pm
requires:
  Exporter: 0.60
  HTML::Selector::XPath: 0.03
  HTML::TableExtract: 2.1
  LWP::UserAgent: 5.834
  URI: 0
  Web::Scraper: 0.24
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/www-mobilecarrierjp/issues
  homepage: https://github.com/tokuhirom/www-mobilecarrierjp
  repository: git://github.com/tokuhirom/www-mobilecarrierjp.git
version: 0.64
x_contributors:
  - 'mattn <mattn@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'clouder <clouder@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'otsune <otsune@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'lopnor <lopnor@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'hirose31 <hirose31@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'kazeburo <kazeburo@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'kan <kan@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'tokuhirom <tokuhirom@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'Kimura <takefumi@chinge.coil>'
  - 'Masahiro Chiba <nihen@megabbs.com>'
  - 'yamaguchi.toru <zigorou@cpan.org>'
  - 'Seiji Harada <liptonteask@gmail.com>'
  - 'noblejasper <nobjas@gmail.com>'
  - 'tnj <kitakore@gmail.com>'
  - 'takuya yamamoto <y.takuan@gmail.com>'
  - 'Masahiro Honma <hiratara@cpan.org>'
  - 'Keiji, Yoshimi <walf443@gmail.com>'
  - 'nyarla <nyarla@thotep.net>'
  - 'tokuhirom <tokuhirom@gmail.com>'
