---
abstract: 'scrape mobile carrier information'
author:
  - 'Tokuhiro Matsuno <tokuhirom gmail com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MobileCarrierJP
no_index:
  directory:
    - inc
    - t
recommends:
  CAM::PDF: 0
requires:
  Exporter: 0.60
  Filter::Util::Call: 0
  HTML::Selector::XPath: 0.03
  Web::Scraper: 0.24
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
